### ISSUE TITLE
Invalid signature base string in oauth v1.0a signature tool?

### ISSUE THREAD

**Issue by aWildElephant** [DinoChiesa/DinoChiesa.github.io#1]
Hello,

I have used your oauth v1.0a tool to try and figure out why the signature generated by my own code was refused by a twitter API. It helped me a great deal to get it to work.

I noticed that the signature base string differs from what twitter actually expects. I'd like to know if this is specific to twitter or a quirk in the signature tool.

**Input (missing parameters are left empty)**
HTTP Method: POST
URL: https://api.twitter.com/1.1/account_activity/all/dev/webhooks.json
Query param string: url=https://this-is-not-the-actual-url-I-used/twitter
consumer key: A
consumer secret: B
token: C
token secret: D
timestamp: 1548161711
nonce: sh6oxp444tn

**Signature base string computed by the tool**
POST&https%3A%2F%2Fapi.twitter.com%2F1.1%2Faccount_activity%2Fall%2Fdev%2Fwebhooks.json&oauth_consumer_key%3DA%26oauth_nonce%3Dsh6oxp444tn%26oauth_signature_method%3DHMAC-SHA1%26oauth_timestamp%3D1548161711%26oauth_token%3DC%26oauth_version%3D1.0%26url%3Dhttps%3A%2F%2Fthis-is-not-the-actual-url-I-used%2Ftwitter

**Signature base string accepted by twitter**
POST&https%3A%2F%2Fapi.twitter.com%2F1.1%2Faccount_activity%2Fall%2Fdev%2Fwebhooks.json&oauth_consumer_key%3DA%26oauth_nonce%3Dsh6oxp444tn%26oauth_signature_method%3DHMAC-SHA1%26oauth_timestamp%3D1548161711%26oauth_token%3DC%26oauth_version%3D1.0%26url%3Dhttps%253A%252F%252Fthis-is-not-the-actual-url-I-used%252Ftwitter

As explained in the documentation (https://developer.twitter.com/en/docs/basics/authentication/guides/creating-a-signature) twitter seems to expect the keys and values of the query string to have been percent encoded twice in the signature base string, but the tool only does it once.

Best regards

**Comment by DinoChiesa** [comment]
Yes, you're right. In fact the page skips the initial percent-encoding
step; that works only if there are no percent-encodable characters in the
parameters. If you include a URL in the params, then ... yes, it won't work
properly.

I'll get that fixed today.

**Comment by DinoChiesa** [comment]
ok, I think that problems is fixed now.

**Comment by aWildElephant** [comment]
Looks good, thanks for the quick reply and fix :)
